version: '2.1'

services:
  php:
    container_name: php
    build:
      context: php
      args:
        TIMEZONE: Europe/Kiev
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ../:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: serverName=XM
      FROM_EMAIL: "xm@test.com"
      DATABASE_URL: "mysql://xm:xm@mysql:3306/xm"
      DATABASE_DRIVER: "pdo_mysql"
      YH_FINANCE_API_URL: "https://yh-finance.p.rapidapi.com"
      YH_FINANCE_API_KEY: "932ab9b67dmshbff52e522033627p1ec34ejsna93a6112f8cc"
      YH_COMPANY_SOURCE_URL: "https://pkgstore.datahub.io/core/nasdaq-listings/nasdaq-listed_json/data/a5bc7580d6176d60ac0b2142ca8d7df6/nasdaq-listed_json.json"
      MAILER_DSN: smtp://20dbd63fb64a0d:eb60606267cc7b@smtp.mailtrap.io:2525?encryption=tls&auth_mode=login
    user: ${LOCAL_USER}

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xm
      MYSQL_USER: xm
      MYSQL_PASSWORD: xm

  nginx:
    container_name: nginx
    build:
      context: nginx
    working_dir: /app
    ports:
      - 80:80
    volumes_from:
      - php
    depends_on:
      - php
    volumes:
      - ./.data/nginx/logs:/var/log/nginx
    environment:
      VIRTUAL_HOST: xm.loc
      VIRTUAL_PORT: 80