parameters:
  #DATABASE
  default.database_url: ''
  database.url: '%env(string:default:default.database_url:DATABASE_URL)%'
  default.database_driver: 'pdo_mysql'
  database.driver: '%env(string:default:default.database_driver:DATABASE_DRIVER)%'

  #YAHOO FINANCE API
  default.yh.finance.api_url: ''
  default.yh.finance.api_key: ''
  default.yh.company.source_url: ''
  yh.finance.api_url: '%env(string:default:default.yh.finance.api_url:YH_FINANCE_API_URL)%'
  yh.finance.api_key: '%env(string:default:default.yh.finance.api_key:YH_FINANCE_API_KEY)%'
  yh.company.source_url: '%env(string:default:default.yh.company.source_url:YH_COMPANY_SOURCE_URL)%'

  #MAILER
  default.mailer_dsn: 'null://null'
  mailer_dsn: '%env(string:default:default.mailer_dsn:MAILER_DSN)%'
  default.from_email: ''
  from_email: '%env(string:default:default.from_email:FROM_EMAIL)%'
