imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/.*/Entity/'
            - '../src/Kernel.php'

    App\XM\Presentation\Http\Controller\:
        resource: '../src/XM/Presentation/Http/Controller/'
        tags: ['controller.service_arguments']

    App\XM\Infrastructure\YhFinanceApi\YhFinanceApi:
        arguments:
            - '%yh.finance.api_url%'
            - '%yh.finance.api_key%'
    App\XM\Domain\CompanyService:
        arguments:
            - '%yh.company.source_url%'
    App\XM\Infrastructure\EventListener\SendInfoEmailSubscriber:
        arguments: ['@mailer', '%from_email%']
        tags:
            - { name: kernel.event_subscriber, event: info.email }

